### ISSUE TITLE
Exploratory Data Analysis

### ISSUE THREAD

**Issue by tonyliang19** [tonyliang19/dsci320-group-project#1]
# Main goals
- [x] Perform and submit an analysis of the data set (refernce the Data Abstraction lectures)
- [x] Perform EDA and submit the notebook: must be a python notebook that can run (make sure that you place your data online so that it is read in using a url)

## Abstract

- [x] A high-level overview of the project (~80 words)

## Introduction
- [x] Brief description of project topic and motivation

## Task Analysis

`Stasko’s taxonomy for low-level tasks`

- [x] At least **5** distinct tasks pertaining to at least **4** distinct attributes.
- [x] Sufficient overall complexity that visualizing multiple attributes using multiple views is necessary.
- [x] All tasks must be plausible and must be addressable by the dataset(s) you are using.
- [x] Your tasks must be complex enough that the design requirements in the Overview are met.

## Preliminary Sketches
- [x] Using the 5-step design process you were exposed to in class (e.g. Map, Sketch, Decide, Prototype, Test) submit low-fidelity sketches for each task.
- [x] For each visualization write ~200 words which summarizes:
       - What tasks in your does the visualization address? Are there new ones you should add/have added?
       - How the sketch adheres to theoretical principles

**Comment by tonyliang19** [comment]
Link to [this](https://pages.github.ubc.ca/kemiola/DSCI320-22W2/project/milestone1.html) ^
